### ISSUE TITLE
BlockProt launch warnings

### ISSUE THREAD

**Issue by Levakiv** [spnda/BukkitPlugins#24]
Warning during plugin loading.
Plugins: item-nbt-api-plugin-2.7.1, BlockProt-0.1.7-all.
```[Craft Scheduler Thread - 0/WARN]: [BlockProt] Plugin BlockProt v0.1.7 generated an exception while executing task 2
java.lang.NumberFormatException: For input string: "BlockProt 0"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_275]
        at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_275]
        at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_275]
        at de.sean.blockprot.bukkit.tasks.UpdateChecker$Version.compareTo(UpdateChecker.kt:66) ~[?:?]
        at de.sean.blockprot.bukkit.tasks.UpdateChecker.run(UpdateChecker.kt:27) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

**Comment by spnda** [comment]
Thanks for the report. This was fixed with b3a5f28 and released with version 0.1.8.
